services:
  backend:
    build: ./backend
    container_name: streamsync-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    networks:
      - streamsync-network

networks:
  streamsync-network:
    external: true
