apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  accesskey: bWluaW9hZG1pbg==        # base64 encoded "minioadmin"
  secretkey: bWluaW9hZG1pbg==        # base64 encoded "minioadmin"
